---
- name: Nocodb | Install sqlite
  package:
    name: sqlite3
  when: "nocodb_backend == 'sqlite' "

- include_tasks: postgresql.yml
  when: "nocodb_backend == 'pg' or nocodb_backend == 'postgresql'"

- include_tasks: mariadb.yml
  when: "nocodb_backend == 'mariadb' or nocodb_backend == 'mysql'"
