---
- name: Nocodb | Install sqlite
  ansible.builtin.package:
    name: sqlite3
  when: "nocodb_backend == 'sqlite' "

- name: Nocodb | Include postgresql.yml
  ansible.builtin.include_tasks: postgresql.yml
  when: "nocodb_backend == 'pg' or nocodb_backend == 'postgresql'"

- name: Nocodb | Include mariadb.yml
  ansible.builtin.include_tasks: mariadb.yml
  when: "nocodb_backend == 'mariadb' or nocodb_backend == 'mysql'"
