---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: nocodb-sqlite
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: nocodb-postgresql
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: nocodb-mariadb
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      nocodb-sqlite:
        nocodb_backend: "sqlite"
      nocodb-postgresql:
        nocodb_backend: "pg"
        nocodb_db: { name: "nocodb", user: "nocodb", port: 5432 }
        nocodb_db_url: "pg://localhost:{{ nocodb_db.port }}?user={{ nocodb_db.user }}&password={{ vault_nocodb_db_password }}&d={{ nocodb_db.name }}"
        vault_nocodb_db_password: "dumtestpassword"
      nocodb-mariadb:
        nocodb_backend: "mariadb"
        nocodb_db: { name: "nocodb", user: "nocodb", port: 3306 }
        nocodb_db_url: "mysql2://localhost:{{ nocodb_db.port }}?user={{ nocodb_db.user }}&password={{ vault_nocodb_db_password }}&d={{ nocodb_db.name }}"
        vault_nocodb_db_password: "dumtestpassword"
verifier:
  name: ansible
